[WIP] マップチップが通り抜けできるか定義
turenar/mayfes2018-pikyou pull request #102
Opened 2018-04-25 05:41 UTC by turenar

TODO:
- [ ] 描画上完全にマスに移動してからmapの描画更新を行う
- [ ] 増えた壁の対応 (issue作る)

fixes #80

2018-04-27 03:20 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/feature/mapchip-def

2018-04-29 03:37 UTC, aqla114 requested changes
気になったのはこれぐらいですかね。

2018-04-29 03:37 UTC, aqla114 commented on src/world.ts
> +	public isGoal: boolean;
isDeadとisGoal、constructorで初期化されていないです。
あと、startStopButtonではresetWorldを読んでいるので、resetWorld内で、
```
this.isDead = false;
this.isGoal = false;
```
が必要そうですかね。

2018-04-29 03:37 UTC, aqla114 commented on src/animation-queue.ts
> +	public running: boolean;
runningが、startStopButtonを押した時にresetされてないです。
AnimationQueue内でresetメソッドを生やすか、もしくは`AnimationQueue.clear()`時に`this.running = false;`にして欲しいです。

2018-04-29 05:15 UTC, aqla114 commented
あと、conflict解消もオナシャス。

2018-04-30 00:04 UTC, aqla114 approved these changes
大丈夫そうです。

2018-04-30 00:04 UTC, merged