Add jump function
turenar/mayfes2018-pikyou pull request #114
Opened 2018-05-01 08:00 UTC by eeic19

#108 です。
ジャンプ機能を実装して、とりあえず動きます。実装等での改善箇所があれば指摘お願いします。
アニメーションは仮です。

2018-05-01 11:26 UTC, aqla114 requested changes
軽く見た感じこんなところ。

2018-05-01 11:26 UTC, aqla114 commented on src/character.ts
> +				distance = 2;
何点か。
・isJumpってconstではだめなんですかね。 
・isjump -> isJump
・const distance = isJump ? 2 : 1 の方がきれいっぽい。

2018-05-01 13:30 UTC, turenar commented on src/block-definitions.ts
> +			message0: 'ジャンプする',
このmessageでこのtooltipは繋がらないような

普通にジャンプするで良いと思うけど…………最後を進む強制にすると、ジャンプに設定するじゃないとダメなのか……うーん

2018-05-01 13:30 UTC, turenar commented on src/character.ts
> +			actiontick = function() {
thisの取扱が面倒だから、arrow関数 ```() => {}``` にしておいてください

2018-05-01 13:30 UTC, turenar commented on src/world.ts
> +		if (!distance) {
default parameter使えばきれいなんじゃないかな？

2018-05-01 13:30 UTC, turenar commented on src/character.ts
> +				distance = 2;
壁とか鍵のついたドアを飛び越せる気がするので、通行不可・ジャンプで飛び越せる・通行可の３種類をmapchip definitionのobstacleが取れるようにしないとかもしれない (別issue？

2018-05-02 00:46 UTC, eeic19 commented
上にある問題はおおむね修正しました。
- 壁を越える問題について

現状1マス先も見ているので大丈夫そう…?(手元で確認した限りでは発生しませんでした)

- default parameterについて

IEだと動かない的な問題があるかと思ったんですがどうしましょう

- jumpの仕様について

普通にジャンプしてしまうと進むとの共存が面倒になりそうだったのでこの仕様にしました。
問題がありそうなら旧仕様に戻します。

2018-05-02 02:21 UTC, aqla114 commented on src/block-definitions.ts
> +			message0: 'ジャンプする',
進む強制がどうこうというよりは、ジャンプと進むで２パターンの進むコマンドが存在するのが微妙ではというお気持ちでたぶんこの実装なのでは。

2018-05-02 02:23 UTC, aqla114 commented
default parameter、IEで動かないのワロタ。
jumpの仕様はまあこれでいいのではというお気持ち。

2018-05-02 03:38 UTC, eeic19 commented
よく考えたらアロー関数もES2015なのでどっちにしてもIE無理でした。
ということでdefault parameterで実装しました。

2018-05-02 04:43 UTC, turenar commented on src/block-definitions.ts
> +			message0: 'ジャンプする',
いや、ジャンプと進むは2パターン有っていいと思うけど。進むコマンドの説明文変える必要はあるかもしれないけど。

2018-05-02 04:44 UTC, turenar commented
少なくともコーディングの時点でIEで動くjavascriptの機能かどうかは気にしなくていいです

2018-05-03 06:21 UTC, aqla114 approved these changes

2018-05-03 06:21 UTC, aqla114 commented
僕はいいと思います。

2018-05-05 06:37 UTC, merged