Add the prototype of instrucion_page
turenar/mayfes2018-pikyou pull request #118
Opened 2018-05-01 11:27 UTC by miya789

### 内容
- [[HTML] `instruction.html` の作成 #117](https://github.com/turenar/mayfes2018-pikyou/issues/117)
  - 1.のみ
#### html
- インデントが崩壊していたので出来る限り修正した。
#### css
- cssが個別になっていたのでこれも去年に倣い分割した。

2018-05-01 16:34 UTC, miya789 commented
## 内容
- [[HTML] `instruction.html` の作成 #117](https://github.com/turenar/mayfes2018-pikyou/issues/117)
  - 2.のみ
    - (1/2) `instruction.html` のclass構造を修正した。

2018-05-16 08:19 UTC, AkariAsai approved these changes

2018-05-16 08:20 UTC, AkariAsai commented on assets/css/instructions.css
> +/* .reverse .block-content:nth-child(odd) {
コメントアウトは消していいと思います 😄

2018-05-16 08:23 UTC, AkariAsai commented on assets/instructions.html
> +                                    もし〜するそうでないとき、
日本語がちょっと小学生くらいの子には伝わりにくいかもしれません...

2018-05-16 12:45 UTC, miya789 commented on assets/css/instructions.css
> +    /* margin-left: 20%; */
## 問題
ここですが、
-  本来： `ブロックの説明` に費やす筈のコード
であったにも拘わらず、
-  現在： `あそびかた` や `ブロックの組み立て方` にもdivを適応してしまった
ので、その部分で不要な為にコメントアウトしました

## 展望
-  `あそびかた` や `ブロックの組み立て方` のclass名を、 `block` －＞ `howto` に変更予定

2018-05-17 08:45 UTC, miya789 commented on assets/css/instructions.css
> +    /* margin-left: 20%; */
https://github.com/turenar/mayfes2018-pikyou/issues/173

2018-05-17 10:50 UTC, miya789 commented
## した事( https://github.com/turenar/mayfes2018-pikyou/issues/117 から天才)
1. 形だけ作成
    - [Add the prototype of instrucion_page b7a805f](b7a805f)
    - 入れ子構造が複雑化しているので今年のゲームに合わせて改良
      - [Modify class_struture of instruction_page b8adeb1](b8adeb1)
      - 問題例：「同じclassの中に同じclass名のブロックがある」等
    - [Added temporary files related to css ef571cf](ef571cf)
2. 今年のゲームの説明に変更
    - [Add top_image 4f9973b](4f9973b)
    - [Modify css about block layouts 0478a87](0478a87)
    - [Modify background of top_image d84c1c2](d84c1c2)
    - Modify description about {if, move, find} block
      - 3e0fce3, aafbff6, b7ab41c
3. レイアウトの改良
    - 子供の理解し易いイラスト配置など(#175 )
      - [Add span for comfortable sentence design 12b5d13](12b5d13)
      - [Add alter-class configuration in css 86d13d4](86d13d4)
    - JQueryなどの動作の改良
      - 時間が無いので多分無理 -> (#176 )

2018-05-17 12:08 UTC, AkariAsai commented on assets/instructions.html
> +                                    「ずっとつづける」のブロックにくっついているブロックを<ruby>読<rp>（</rp><rt>よ</rt><rp>）</rp></ruby>んで、とりは<ruby>動<rp>（</rp><rt>うご</rt><rp>）</rp></ruby>きます。
「とり」は昨年の仕様なので変更したほうが良さそう

2018-05-17 12:08 UTC, AkariAsai commented on assets/instructions.html
> +                                    「～かつ～」，「～または～」
めっちゃ細かいですが「,」と「、」は統一したほうが良さそう...?

2018-05-17 12:08 UTC, AkariAsai commented on assets/instructions.html
> +                                    <ruby>同時<rp>（</rp><rt>どうじ</rt><rp>）</rp></ruby>に<ruby>正<rp>（</rp><rt>ただ</rt><rp>）</rp></ruby>しいときを<ruby>表<rp>（</rp><rt>あらわ</rt><rp>）</rp></ruby>します。
「同時に正しい」って伝わるのかな..
プログラミングを勉強したことがあれば「if cond_1 == true and cond_2 == true then」ってことかなと思うのですが、小学生だと「同時に正しい？？」ってなりそう。「両方当てはまる」とかは？

2018-05-17 12:08 UTC, AkariAsai commented on assets/instructions.html
> +                                    どちらかに<ruby>正<rp>（</rp><rt>ただ</rt><rp>）</rp></ruby>しいときを<ruby>表<rp>（</rp><rt>あらわ</rt><rp>）</rp></ruby>します。
どちらかに --> 「どちらかひとつでも」のがわかりやすい気がします

2018-05-17 12:08 UTC, AkariAsai commented on assets/instructions.html
> +                                    キャラが→の<ruby>方向<rp>（</rp><rt>ほうこう</rt><rp>）</rp></ruby>を<ruby>向<rp>（</rp><rt>む</rt><rp>）</rp></ruby>きます。
キャラクターが矢印(→, ←, ↑, ↓)の方向を向きます、って書いたほうが混乱しないかも（一方向だけだとちょっと）

2018-05-17 12:08 UTC, AkariAsai commented on assets/instructions.html
> +                                    <ruby>星<rp>（</rp><rt>ほし</rt><rp>）</rp></ruby>のところにたどりつけるようにプログラムを<ruby>組<rp>（</rp><rt>く</rt><rp>）</rp></ruby>みましょう！
今年ってゴール星でしたっけ

2018-05-17 12:08 UTC, AkariAsai commented on assets/instructions.html
> +                                    「スタート」をおすと、プログラムを<ruby>読<rp>（</rp><rt>よ</rt><rp>）</rp></ruby>んでとりが<ruby>動<rp>（</rp><rt>うご</rt><rp>）</rp></ruby>きます。
とり --> キャラ

2018-05-17 12:24 UTC, miya789 commented on assets/instructions.html
> +                                    「ずっとつづける」のブロックにくっついているブロックを<ruby>読<rp>（</rp><rt>よ</rt><rp>）</rp></ruby>んで、とりは<ruby>動<rp>（</rp><rt>うご</rt><rp>）</rp></ruby>きます。
「あそびかた」を直す際に～～～します！
追記）やっぱり面倒なので修正しました

2018-05-17 12:42 UTC, AkariAsai approved these changes

2018-05-17 13:11 UTC, aqla114 requested changes
全体を通して
* styleがぶっ壊れてるのはこれから何とかして欲しい。
* 若干読みづらさがあるのでブロックの説明間に薄い色のborder-lineがあると嬉しいかもしれない。
* 表現の統一を。
* ブロックの名前（<h4>タグで囲われてる部分）はブラウザのウィンドウサイズにもよるかもしれんけど、流石に1行で表示された方が見やすい（もしくは適切な文節で改行して欲しい）。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                いまとりがどこにいるのかを<ruby>調<rp>（</rp><rt>しら</rt><rp>）</rp></ruby>べることが<ruby>出来<rp>（</rp><rt>でき</rt><rp>）</rp></ruby>るブロックたちです。
* 「とり」->「キャラクター」
* 「どこにいるのかを調べることができる」は不正確。なぜなら、どこにいるか調べる以外のことも調べられるので。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    <span>「もしも」のみぎにくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていること</span>と
他の場所では「みぎ」は漢字で「右」と表示されているので統一すべき。
漢字の「右」「左」は小学一年生で習う漢字であるためほぼ全ての小学生が読めると想定して、「右」「左」は全て「漢字＋ルビ」にすべきだと思う。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    が<ruby>同<rp>（</rp><rt>おな</rt><rp>）</rp></ruby>じなら、「する」のみぎにくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていることを、キャラがやります。
ブロックに「する」という単語は存在していない。「もしも〜ならば」しかない。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    <span>「～かつ」のひだりにくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていること</span>と
「ひだり」「みぎ」

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    <span>「～かつ」のひだりにくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていること</span>と
「ひだり」「みぎ」
※これ以降は指摘しても無駄に増えるだけなので自分で探して修正してくれると嬉しいです。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    「～かつ～」
![image](https://user-images.githubusercontent.com/26360576/40178108-81d50102-5a1b-11e8-8e0f-bd820f6eac2c.png)
表示がぶっ壊れてるんですけど、これは...多分cssが悪そう。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    <span>「～ではない」のひだりにくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていること</span>が
「「〜ではない」の左」というかどちらかといえば中だよね...

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    <span><ruby>今<rp>（</rp><rt>いま</rt><rp>）</rp></ruby>のキャラのじょうたい</span>
「キャラの状態と等しい」って表現なんだけど、後述の「かつ」「または」「〜ではない」では「〜が正しいとき」とか「〜が間違っている時」とかいう表現してるし、こっちもそれでいいのでは。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    もしも〜ならば（if<ruby>文<rp>（</rp><rt>ぶん</rt><rp>）</rp></ruby>）
if else, elseの説明もして欲しい。特に、ifブロックの歯車をクリックすると出てくることとか。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    <ruby>同時<rp>（</rp><rt>どうじ</rt><rp>）</rp></ruby>に<ruby>正<rp>（</rp><rt>ただ</rt><rp>）</rp></ruby>しいときを<ruby>表<rp>（</rp><rt>あらわ</rt><rp>）</rp></ruby>します。
上で「ばあいわけ」って言葉を使ってるわけだし、「とき」じゃなくて「ばあい」でいいのでは。他の箇所も同じく。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    キャラが→の<ruby>方向<rp>（</rp><rt>ほうこう</rt><rp>）</rp></ruby>を<ruby>向<rp>（</rp><rt>む</rt><rp>）</rp></ruby>きます。
矢印にルビで「上」とか「左」とかつけてもいいかもしれない（これは提案）

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    キャラはすすむときにジャンプします。
キャラ「は」->「が」

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    「1マスすすむ」の<ruby>前<rp>（</rp><rt>まえ</rt><rp>）</rp></ruby>にあると、
「次に「１マスすすむ」時に、ジャンプしてもう１マス飛び越えます」とかの方が分かりやすいかも（この表現がベストかは微妙なのでちょっと考えて欲しい）。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    <ruby>矢印<rp>（</rp><rt>やじるし</rt><rp>）</rp></ruby>の方向で1マスぶん<ruby>離<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>はなれたところに「カベ、トビラ」があるかどうかを<ruby>調<rp>（</rp><rt>しら</rt><rp>）</rp
* 「１マスぶん離れたところで」は流石に分かりにくい。「１マス先に」とかでいいのでは。
* 「カベやトビラといったすすむことができないものが」とか、これが進めないかどうかを調べることを明示して欲しい。
* 「あるかどうか」、正確には「ないかどうか」。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    キャラの向いている方向で1マスぶん<ruby>離<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>はなれたところに「カベ、トビラ」があるかどうかを<ruby>調<rp>（</rp><rt>しら</rt><rp>）</rp></ruby>べます。
同上。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    キャラの向いている方向で1マスぶん<ruby>離<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>はなれたところに「落とし穴」があるかどうかを<ruby>調<rp>（</rp><rt>しら</rt><rp>）</rp></ruby>べます。
同上。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    <span class="alter">赤</span>マーカーにいる
上は「カギ/オタカラ」ってやってるしここもスラッシュで4色全部示しては。

2018-05-17 13:11 UTC, aqla114 commented on assets/instructions.html
> +                                    キャラの向いている方向で1マスぶん<ruby>離<rp>（</rp><rt>はな</rt><rp>）</rp></ruby>はなれたところに「カベ、トビラ」があるかどうかを<ruby>調<rp>（</rp><rt>しら</rt><rp>）</rp></ruby>べます。
あと、ここは「カベ、トビラ」ではなく「カベやトビラ」（おそらく、andかorかで表現を分けている）。

2018-05-17 13:11 UTC, aqla114 commented on assets/css/reset.css
>      background-color:#ff9;
流石に灰色は文字も読みにくいし、絵面もよくないから変えて欲しい。

2018-05-17 13:13 UTC, miya789 commented on assets/css/reset.css
>      background-color:#ff9;
選択肢って言うのを表現したかったんですけど、「/」が良いですかね？

2018-05-17 14:15 UTC, aqla114 commented on assets/css/reset.css
>      background-color:#ff9;
ごめん、言葉が足りなかった。
背景色変えるのはいいと思うので灰色はやめて別の色にして欲しいという要求でした。

2018-05-17 14:16 UTC, aqla114 commented
余力があれば、ブロックの説明にコストのことも書いて欲しさがある。

2018-05-17 14:22 UTC, miya789 commented
@aqla114 すみません、コストらへん、理解が追い付いてないので、教えてもらってもいいでしょうか…？

2018-05-17 14:22 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-17 14:23 UTC, miya789 commented
確かに見返したら、場所によって人格が変わっていて支離滅裂なので、表現を統一します。
拙いPRなのに丁寧にありがとうございました。

2018-05-17 14:42 UTC, aqla114 commented
コストについて
* ブロックにはそれぞれ「コスト」が設定されている。
* ブロックを繋げるとそのコスト分、所持金（ゴールド）が減っていく。
* より小さい総コスト、つまり、より所持金を残した状態でゴールするのがハイスコアの鍵。

こんな感じですかね。

2018-05-17 14:42 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-17 14:53 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-17 15:45 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-17 15:47 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-17 15:54 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-17 17:10 UTC, miya789 commented
> コストについて
> 
> ブロックにはそれぞれ「コスト」が設定されている。
> ブロックを繋げるとそのコスト分、所持金（ゴールド）が減っていく。
> より小さい総コスト、つまり、より所持金を残した状態でゴールするのがハイスコアの鍵。
> こんな感じですかね。

- Add description about cost 3814450
- やりましたので確認お願い致します。

2018-05-17 17:19 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-18 02:24 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-18 06:20 UTC, aqla114 requested changes
とりあえず途中までレビューしちゃったので、コメントだけ付けてます。後半はまだ見てません。見て欲しいタイミングでまた声かけてください。

2018-05-18 06:20 UTC, aqla114 commented on assets/instructions.html
> +                        ブロックを<ruby>組<rp>（</rp><rt>く</rt><rp>）</rp></ruby>み<ruby>合<rp>（</rp><rt>あ</rt><rp>）</rp></ruby>わせてプログラムを<ruby>組<rp>（</rp><rt>く</rt><rp>）</rp></ruby>み、キャラに<ruby>星<rp>（</rp><rt>ほ
鳥じゃないし星じゃないしさくらんぼじゃないでしょ💢

2018-05-18 06:20 UTC, aqla114 commented on assets/instructions.html
> +                                    ステージを<ruby>選<rp>（</rp><rt>えら</rt><rp>）</rp></ruby>んで「ゲームスタート」をおすとゲームが<ruby>始<rp>（</rp><rt>はじ</rt><rp>）</rp></ruby>まります。
「矢印ボタンでステージをえらんで」とかの方が良い気もする。

2018-05-18 06:20 UTC, aqla114 commented on assets/instructions.html
> +                                    「スタート」をおすと、プログラムを<ruby>読<rp>（</rp><rt>よ</rt><rp>）</rp></ruby>んでキャラが<ruby>動<rp>（</rp><rt>うご</rt><rp>）</rp></ruby>きます。
「プログラムを読んで」は分かりにくい気がする。「ブロックで指示したとおりに」とか、「組み立てたブロックを読んで」とか。

2018-05-18 06:20 UTC, aqla114 commented on assets/instructions.html
> +                                        <ruby>右側<rp>（</rp><rt>みぎがわ</rt><rp>）</rp></ruby>でブロックを<ruby>組<rp>（</rp><rt>く</rt><rp>）</rp></ruby>み<ruby>立<rp>（</rp><rt>た</rt><rp>）</rp></ruby>ててプログラムを<ruby>作<
「プログラムを組み立てます」プログラムとはなんですか？ってなるので、普通に「ブロックを組み立ててキャラクターを動かします」とかで。

2018-05-18 06:20 UTC, aqla114 commented on assets/instructions.html
> +                                    ブロックにはそれぞれ「コスト」を持っています。<br>
「には」→「は」

2018-05-18 06:20 UTC, aqla114 commented on assets/instructions.html
> +                                    <ruby>一番<rp>（</rp><rt>いちばん</rt><rp>）</rp></ruby><ruby>小<rp>（</rp><rt>ちい</rt><rp>）</rp></ruby>さいコストでゴールできるとハイスコアです！がんばってめざしましょう！
一番小さいコストでクリアできるとハイスコアな訳ではない。「できるだけコストが小さくなるようにブロックを組みましょう！」とかにする。
あと、これは変更点なので追記してほしいんだけど、所持ゴールドが0を下回るとスタートできなくしたのでその旨を記述してほしい。

2018-05-18 06:20 UTC, aqla114 commented on assets/instructions.html
> +                                    ブロックをくっつけると、そのブロックの「コスト」の<ruby>分<rp>（</rp><rt>ぶん</rt><rp>）</rp></ruby>だけ、ゴールドが<ruby>少<rp>（</rp><rt>すく</rt><rp>）</rp></ruby>なくなります。
「所持ゴールドがへります」とかでいいのでは。

2018-05-18 07:18 UTC, aqla114 commented
あと、「キャラ」を「キャラクター」にして欲しいです。

2018-05-18 07:55 UTC, aqla114 requested changes
全体として
* 「キャラ」ではなく「キャラクター」が適切。他の場所では「キャラクター」と呼んでいる。

2018-05-18 07:55 UTC, aqla114 commented on assets/instructions.html
> +                                    <span>「もしも」の<ruby>右<rp>（</rp><rt>みぎ</rt><rp>）</rp></ruby>にくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていること</span>が
ここだけboldになってるけど、下のelse if, elseの「〜に書かれていること」はboldになってないんだけど、統一しないん？

2018-05-18 07:55 UTC, aqla114 commented on assets/instructions.html
> +                                    <ruby>正<rp>（</rp><rt>ただ</rt><rp>）</rp></ruby>しい場合に、<br>
「場合」→「ばあい」（他も同様）

2018-05-18 07:55 UTC, aqla114 commented on assets/instructions.html
> +                                        <span>「それ<ruby>以外<rp>（</rp><rt>いがい</rt><rp>）</rp></ruby>でもしも」の<ruby>右<rp>（</rp><rt>みぎ</rt><rp>）</rp></ruby>にくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></
else ifなので、elseであるという説明が欲しい。現状の説明だと、else if (A)が正しければ任意の場合に実行されるようになっている。「ifが正しくないばあいに〜」みたいな前置きが欲しい。

2018-05-18 07:55 UTC, aqla114 commented on assets/instructions.html
> +                                    「1マスすすむ」の<ruby>前<rp>（</rp><rt>まえ</rt><rp>）</rp></ruby>にあるとき、
流石に日本語がわかりにくい。この前のレビューで書いた表現じゃダメでしたか？

「次に「１マスすすむ」時に、ジャンプしてもう１マス飛び越えます」

2018-05-18 07:55 UTC, aqla114 commented on assets/instructions.html
> +                                いまキャラがどこにいるのかを<ruby>調<rp>（</rp><rt>しら</rt><rp>）</rp></ruby>べることが<ruby>出来<rp>（</rp><rt>でき</rt><rp>）</rp></ruby>るブロックたちです。
「いまキャラがどこにいるかを調べる」は正確ではない。キャラがどこにいるか以外も調べられるので。

2018-05-18 07:59 UTC, miya789 commented on assets/instructions.html
> +                                    <span>「もしも」の<ruby>右<rp>（</rp><rt>みぎ</rt><rp>）</rp></ruby>にくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていること</span>が
設定増やしたら機能しなくなりました…
原因追求しますが、不能ならばbold自体諦めます

2018-05-18 08:13 UTC, aqla114 commented on assets/instructions.html
> +                                    <span>「もしも」の<ruby>右<rp>（</rp><rt>みぎ</rt><rp>）</rp></ruby>にくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていること</span>が
単純にcssのセレクタの表記がおかしいのでは？という気持ちもあるけど、まあボールドなくてもいいと思う。

2018-05-18 09:52 UTC, miya789 commented on assets/instructions.html
> +                                    「1マスすすむ」の<ruby>前<rp>（</rp><rt>まえ</rt><rp>）</rp></ruby>にあるとき、
個人的に、「次にすすむ時ジャンプする」が「１マスすすむ」の前に置かれる事で、
「１マスすすむ」が2マス進むように変化すると認識してました。

2018-05-18 09:53 UTC, miya789 commented on assets/instructions.html
> +                                    「1マスすすむ」の<ruby>前<rp>（</rp><rt>まえ</rt><rp>）</rp></ruby>にあるとき、
取り敢えずその通りにします。

2018-05-18 10:19 UTC, aqla114 commented on assets/instructions.html
> +                                    「1マスすすむ」の<ruby>前<rp>（</rp><rt>まえ</rt><rp>）</rp></ruby>にあるとき、
その認識は正しいんだけど、外部向けの説明としてはやや不適かなという気持ち(これは個人の感覚なのかもしれないから任せる。申し訳ない)

2018-05-18 10:22 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/Web_create_prototype_of_instruction_page

2018-05-18 10:47 UTC, aqla114 requested changes
他は修正されてていいと思います。

2018-05-18 10:47 UTC, aqla114 commented on assets/instructions.html
> +                                        <ruby>正<rp>（</rp><rt>ただ</rt><rp>）</rp></ruby>しくない<ruby>場合<rp>（</rp><rt>ばあい</rt><rp>）</rp></ruby>でも、<br>
「でも」→「で」

2018-05-18 10:47 UTC, aqla114 commented on assets/instructions.html
> +                                        「その他ならば」の<ruby>右<rp>（</rp><rt>みぎ</rt><rp>）</rp></ruby>にくっついているブロックに<ruby>書<rp>（</rp><rt>か</rt><rp>）</rp></ruby>かれていることを、キャラクターがやります。
ここだけボールド効いてない。

2018-05-18 11:04 UTC, miya789 commented on assets/instructions.html
> +                                        <ruby>正<rp>（</rp><rt>ただ</rt><rp>）</rp></ruby>しくない<ruby>場合<rp>（</rp><rt>ばあい</rt><rp>）</rp></ruby>でも、<br>
「でも」にする事で、
 `「「もしも」の 右みぎ にくっついているブロックに 書か かれていること 」` が正しくなくても動ける！
という逆説のニュアンス(?)を持たせようと思ってましたが、ダメでしょうか？

2018-05-18 13:21 UTC, aqla114 requested changes
１箇所だけ気になったけど、他はいいと思います。そこだけ修正してくれたら、approveします。

2018-05-18 13:21 UTC, aqla114 commented on assets/instructions.html
> +                                    がんばってめざしましょう！
ここ、何を目指すのかわからないので「がんばってゴールをめざしましょう！」とか何を頑張るのか書くか、消すかして欲しい。

2018-05-18 22:18 UTC, miya789 commented
#182も之が終わったらMergeおねがいします。
masterをそれのbranchにMergeして更新すれば正常に動作するとアモイます
暫く試験で返信できなくなります…

2018-05-19 00:08 UTC, aqla114 approved these changes

2018-05-19 00:09 UTC, merged