[WIP]Add stages
turenar/mayfes2018-pikyou pull request #125
Opened 2018-05-07 07:47 UTC by eeic19

ゲームのステージの作成です。

2018-05-12 13:29 UTC, aqla114 commented
@eeic19 
要望
1.僕をレビュワーに指定して欲しい。
2.コミットログがあまりに汚すぎるので、できれば修正して欲しい。

2018-05-13 02:33 UTC, turenar approved these changes

2018-05-13 02:42 UTC, turenar requested changes
何が起こってるんだと思ったらrebaseされる前のfix-designの内容が入っているのか、、、

rebaseされるまえのfix-designがマージされたコミット (commit: 00f101e) は最低限除去してください。
やり方が分からなければぼくかどやくんでやっちゃいます

2018-05-14 05:48 UTC, eeic19 commented
なんだこれ…(反省している)
さすがに荒れすぎていて復元できる気がしないので一旦閉じて別ブランチで復元します...

2018-05-14 05:48 UTC, closed without merging