[WIP]Add new stages
turenar/mayfes2018-pikyou pull request #145
Opened 2018-05-14 06:53 UTC by eeic19

ステージ作成の復元です。

2018-05-14 08:24 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/add-new-stages

2018-05-15 08:06 UTC, eeic19 commented
ひとまず完成しました。

2018-05-16 00:11 UTC, aqla114 requested changes
こんな感じですかね。ちょっと、このPRさっさとMergeしたさあるので、僕の方で巻き取っちゃいます。

2018-05-16 00:11 UTC, aqla114 commented on src/stages.ts
> +		description: 'キャラクタを動かそう',
いや、確かに我々情報屋は基本最後に伸ばす棒つけないけど、世間一般に「キャラクタ」ではなく「キャラクター」ではwww

2018-05-16 00:11 UTC, aqla114 commented on src/stages.ts
> +		description: 'おたからをどうやって取ろう',
ここだけdescriptionの言葉の立場が違う。今までは呼びかけだったが、ここではdescriptionの発言者が悩んでいるように読める。
「オタカラをどうやってとるか考えよう」にした方が良さそう。（今、ブロックの表記が「オタカラ」になっているのでそれに合わせたい）。

2018-05-16 00:11 UTC, aqla114 commented on src/stages.ts
> +		description: '穴があったらジャンプしよう',
「穴はジャンプで飛びこえよう」とか。

2018-05-16 00:18 UTC, aqla114 commented
mergeします。

2018-05-16 00:18 UTC, aqla114 approved these changes

2018-05-16 00:19 UTC, merged