ブロックの表記を小学生向きに変更しました
turenar/mayfes2018-pikyou pull request #152
Opened 2018-05-14 10:27 UTC by reito48916

#133 
ブロックのmessage、tooltipを小学生向きに変更しました。
if else、and orについては、初期化処理をドキュメントから引っ張ってきて
編集してあります。

2018-05-15 00:24 UTC, aqla114 requested changes
おおよそ大丈夫だと思いました。表現で気になったところが何個かあるので、修正して欲しいというよりはどう思う？って感じです。

2018-05-15 00:24 UTC, aqla114 commented on src/block-definitions.ts
> +			tooltip: 'この下に左のブロックを加えて、いろんなチェックを作ろう',
「いろんなチェックを作ろう」は日本語として微妙におかしい感がある。
「うまくチェックができるようにしよう」とかかなぁ。

2018-05-15 00:24 UTC, aqla114 commented on src/block-definitions.ts
> +			tooltip: '１つ前のチェックではもれたけれど、もしも…',
「1つ前の「もしも」に当てはまらない場合で、もしも」とか。

2018-05-15 00:24 UTC, aqla114 commented on src/block-definitions.ts
> +		this.setTooltip('決めた方向の１マス先にすすめるかチェックします');
「決めた方向」。ここは「特定の方向」でもいい気がする（小学生わからないかな？）

2018-05-15 00:24 UTC, aqla114 commented on src/block-definitions.ts
> +		this.setTooltip('少年が向いている方向の１マス先にカベがあるかチェックします');
「カベやトビラ」

2018-05-15 00:24 UTC, aqla114 commented on src/block-definitions.ts
> +		this.setTooltip('少年がアイテムのあるマスに入っているかチェックします');
「入っているか」->「いるか」でいいのでは。

2018-05-15 00:24 UTC, aqla114 commented on src/block-definitions.ts
> +		this.setTooltip('決めた方向の１マス先にすすめるかチェックします');
「ある方向」でもいいかも。

2018-05-15 02:56 UTC, turenar commented on src/block-definitions.ts
> +			message0: '少年がこの下につながった動きをくりかえします',
どうも冗長な印象を受ける……主語消していいと思うけど、どうかな？

できれば、下に繋げる形じゃなくて、繰り返しのかたち (ifと同じように右に繋げる形) にしてもらえますか

2018-05-15 02:56 UTC, turenar commented on src/block-definitions.ts
> +			message0: 'ジャンプ',
次のすすむはジャンプ、くらいに明示的にして欲しい

2018-05-15 07:09 UTC, reito48916 commented on src/block-definitions.ts
> +			tooltip: 'この下に左のブロックを加えて、いろんなチェックを作ろう',
「この下に左のブロックを加えて、ふくざつなチェックができます」としました。
なぜかこのブロックだけツールチップが説明ではなくヒント？っぽい口調になっていたので統一しました
このブロックの役割的に「口調はそのままでええやろ」ということであれば変えますがどうでしょう

2018-05-15 07:09 UTC, reito48916 commented on src/block-definitions.ts
> +			tooltip: '１つ前のチェックではもれたけれど、もしも…',
「１つ前の「もしも」に当てはらない場合に、他の「もしも」をチェックします」としました。
長すぎるでしょうか？

2018-05-15 07:09 UTC, reito48916 commented on src/block-definitions.ts
> +		this.setTooltip('決めた方向の１マス先にすすめるかチェックします');
矢印を選べるブロックのツールチップは「矢印の方向...」に統一しました。
アイテムは「アイテム...」、マーカーは「選んだマーカー...」となっていますがどうでしょう

2018-05-15 07:09 UTC, reito48916 commented on src/block-definitions.ts
> +		this.setTooltip('少年が向いている方向の１マス先にカベがあるかチェックします');
すみませんでした。

2018-05-15 07:09 UTC, reito48916 commented on src/block-definitions.ts
> +		this.setTooltip('少年がアイテムのあるマスに入っているかチェックします');
このツールチップの説明が不適切なのは確かです。
その上で、このブロックのメッセージ（ブロックの表記）を「〇〇を見つけた」にしている通り、
プログラムを知らないユーザからするとこの条件を使うタイミングは「アイテムのマスについた時」
というより「アイテムを取ったとき」と考えるほうが自然だと思います。
なので、「今アイテムを取ったところかどうかチェックします」としてみました。分かりにくいでしょうか？

2018-05-15 07:09 UTC, reito48916 commented on src/block-definitions.ts
> +			message0: '少年がこの下につながった動きをくりかえします',
このブロックについては「この下につなげた動きがくり返されます」として、その他のブロックからもとりあえず一度「少年」の表記をなくしました。ブロックの形の変更については、取り組んでみますがすぐにできるか分からないのでひとまずおいておきます。

2018-05-15 07:10 UTC, reito48916 commented on src/block-definitions.ts
> +			message0: 'ジャンプ',
「次にすすむ時ジャンプする」としました。

2018-05-15 07:16 UTC, reito48916 commented
指摘された部分の修正と、昨日の時点で出来ていなかった、忘れていた次の点を編集しました
・ifブロックのmutator（歯車機能）でelse if、elseをブロックに追加した際のメインブロックの「他でもしも」「他」という表示
・notブロックのツールチップ

2018-05-15 09:59 UTC, reito48916 commented on src/block-definitions.ts
> +			message0: '少年がこの下につながった動きをくりかえします',
ブロックの形変更、できました。

2018-05-15 10:05 UTC, reito48916 commented
code jeneraterorを編集して、executeブロックをネスト状にしました。
それに伴いblock definitionも少しいじりました。

2018-05-16 00:59 UTC, aqla114 approved these changes

2018-05-16 01:00 UTC, aqla114 commented
いいと思います！

2018-05-16 01:00 UTC, aqla114 commented
どうしても気になったらあとで直せばいいと思うのでmergeしちゃいます。

2018-05-16 01:00 UTC, merged