Fix code generators
turenar/mayfes2018-pikyou pull request #154
Opened 2018-05-15 00:58 UTC by eeic19

#146 の修正。
これで直っているとは思いますが何かあったらお願いします。

2018-05-15 02:31 UTC, turenar requested changes

2018-05-15 02:31 UTC, turenar commented on src/code-generators.ts
>  	return [code, (Blockly.JavaScript as any).ORDER_MEMBER];
https://developers.google.com/blockly/guides/create-custom-blocks/operator-precedence
のとおり、ORDER_EQUALITYにすると括弧をつける必要がなくなるのではないでしょうか

2018-05-15 03:07 UTC, eeic19 commented
修正しました。
今回のbugに直接関係しないcheckも変更してあります。

2018-05-15 06:26 UTC, turenar approved these changes

2018-05-16 00:24 UTC, merged

2018-05-16 00:26 UTC, turenar commented
関数呼び出しとかはORDER_MEMBERのままで良い気がするけれど、orderが高い分には問題なさそう (よく理解してないならORDER_NONEでいいと書いてある)

というのを昨日書いたつもりだったけどネットワークがダメすぎて書けてなかった