ブロックのツールチップにコスト説明を追加
turenar/mayfes2018-pikyou pull request #160
Opened 2018-05-16 03:02 UTC by reito48916

ifブロックが冗長のような気もするので何か案があったらお願いします。

2018-05-16 04:13 UTC, turenar commented
else if、elseのほうに説明移してもいい気がする？

2018-05-16 05:22 UTC, reito48916 commented
else if、 elseにコスト3点と書いておき、ifブロックにelse ifなどを追加するとそれら×3をプラスした数字をコストとしてifブロックのツールチップに表示するようにしました。

2018-05-16 05:23 UTC, ghost commented
deployed! https://turenar.xyz/mayfes-pikyou/add-cost-description

2018-05-16 06:29 UTC, aqla114 requested changes
* これはぼくが指定してなかったから申し訳ないんだけど、コストの次元は無次元、つまり、単位無しを想定していたので全ての「点」を除いてくれると嬉しい。
* これも僕のミスで大変申し訳ないんだけど、yarn formatでblockly-mainに修正が発生しちゃうの、僕の方で解決しておくので、「formatでblockly-mainも変わってました」のコミットだけrebaseで消して欲しい。

2018-05-16 06:29 UTC, aqla114 commented on src/block-definitions.ts
> +				'自分で決めたチェックのうち、当てはまっている行動をします\nコスト：' + (5 + mutatorCount * 3) + '点'
ここなんですけど、Template Stringというものを使うと綺麗にかけると思います。
具体的には、`自分で決めたチェックのうち、当てはまっている行動をします\nコスト：${ 5 + mutatorCount * 3} 点`と書くことで文字列に数式を埋め込める。「`」はバッククォートで、「'」とは違うので注意。${}のなかに数式を書く。

2018-05-16 06:29 UTC, aqla114 commented on src/block-definitions.ts
> +		var mutatorCount = 0;
個人的にはvarよりlet使って欲しいかも（動かなかったらvarで良いです）
Javascrpitとかではvarの使用は基本的に推奨されていないので。

2018-05-16 06:30 UTC, aqla114 commented
一応、コストを無次元にする理由としては、小学生の常識だと「点は高い方がいい」という認識があると思うので、紛らわしさを無くしたいからです。

2018-05-16 08:49 UTC, reito48916 commented
表記をゴールドにしただけなので最初からあるブロックに表示される数字は「現在のコスト」のままです。
これを「基礎点（ゲタ）ーコスト」に変更するにはステージとの連繋が必要です。

2018-05-16 08:55 UTC, aqla114 commented
巻き取ります。

2018-05-17 02:42 UTC, aqla114 commented
特に問題なければapproveしてmergeしちゃいます。

2018-05-17 03:53 UTC, aqla114 approved these changes

2018-05-17 03:53 UTC, aqla114 commented
mergeしちゃいます。

2018-05-17 03:53 UTC, merged