キャラクターの移動メソッドの実装とblocklyとのつなぎこみ実装
turenar/mayfes2018-pikyou pull request #22
Opened 2018-03-07 02:54 UTC by aqla114

move, setDirection, stop の3つに関して、メソッドの実装とblocklyとのつなぎこみを行った。
@typesを更新しているのでまた`yarn`を叩いてください。

<a href="https://gyazo.com/46f91bcaf766e96e417c6530b0e04ba7"><img src="https://i.gyazo.com/46f91bcaf766e96e417c6530b0e04ba7.gif" alt="https://gyazo.com/46f91bcaf766e96e417c6530b0e04ba7" width="960"/></a>

2018-03-07 02:55 UTC, aqla114 commented
あ、lint忘れてた。めっちゃ怒られてるんで今修正してpushし直します。

2018-03-07 03:05 UTC, aqla114 commented
このchecks failedは、僕の更新した@typesが`yarn`で更新されてないために起きてるっぽいですね。
具体的には、「`Blockly.Javascript`などというプロパティはありませんよﾜﾗｲ」なんですけど、yarnとかいうの割とレポジトリに加えた変更がすぐに反映されなくて悲しい。

2018-03-07 06:25 UTC, turenar requested changes
https://github.com/turenar/mayfes2018-pikyou/issues/23#issuecomment-371035755

2018-03-08 06:48 UTC, aqla114 commented
@turenar 
`check`通ったんでreviewとmergeお願いします。

2018-03-08 07:31 UTC, turenar approved these changes

2018-03-08 07:31 UTC, merged

2018-03-08 07:32 UTC, turenar commented
[![LGTM](http://lgtm.in/p/m57GNewdq)](http://lgtm.in/i/m57GNewdq)