スタート/ストップボタンを追加した。
turenar/mayfes2018-pikyou pull request #37
Opened 2018-03-10 09:15 UTC by aqla114

#25 です。
押すたびにスタートとストップが変わって実行状態が変化するようにしました。画像は仮置きなのでSpriteのサイズもガバガバです。
どういう風に処理を切り分けるか悩んだ（具体的には、isRunning変数をどこで管理するのかと、reloadButtonメソッドにどこまで処理をやらせるのか）ので、気になるところあったら言ってくれると嬉しいです。

2018-03-10 09:53 UTC, turenar requested changes

2018-03-10 09:53 UTC, turenar commented on src/button.ts
> +export class Button extends enchant.Sprite {
Buttonはちょっと抽象的すぎるので、GameStateButtonとかなんかそれっぽい名前にして欲しさisある

2018-03-10 09:53 UTC, turenar commented on src/enchant-main.ts
> +		let isRunning = false;
確かに、外出ししたほうが良い気はする。isRunningは色んな所から呼び出されそう

isRunningの変更をpub-subで受け取れるようにすると便利なのかもしれない (単にややこしくなるだけかもしれない

2018-03-10 09:53 UTC, turenar commented on src/enchant-main.ts
> +		button.addEventListener('touchstart', function() {
Buttonクラスに移して良いと思う

2018-03-10 09:53 UTC, turenar commented on src/button.ts
> +export class Button extends enchant.Sprite {
あと、classならたぶんdefault exportにしていいと思う

2018-03-10 09:53 UTC, turenar commented on src/scenes.ts
> +export function initScene(character: Character, button: Button) {
SceneファイルでinitSceneするよりは、別のScreenみたいなクラスを作って、enchant-mainから画面系のコードとかを移したほうが見た目的に良さそう

2018-03-10 13:04 UTC, aqla114 commented on src/enchant-main.ts
> +		button.addEventListener('touchstart', function() {
ここをButtonクラスに移すと、Buttonのコンストラクタにcharacterを渡すことになってしまって、コンポーネントの関係的に気持ち悪さありません？（個人の感想）
後の`character.on`も`enchant-main`内で呼ばれてるので、ここはこのまま`enchant-main`内に記述するのがいいのかなと個人的には思っています。
後、`core.pause()`に関しては今後、`Top`やら`StageSelecting`なるシーンが実装された際にどう配置するか未定なのでとりあえずここに置いときたいです。

2018-03-10 13:06 UTC, aqla114 commented on src/enchant-main.ts
> +		let isRunning = false;
`enchant.Core`クラスを継承してisRunningを持たせるのが丸そうな気がするんですけど、どうでしょう。

2018-03-10 13:11 UTC, aqla114 commented on src/scenes.ts
> +export function initScene(character: Character, button: Button) {
ですねぇ...
現状まだプレイ画面以外のシーンが出来ていないので、Issue立てて置いてあとで実装ですかね。
上の`isRunnnig`案件と合わせて、`Core`クラス拡張してシーン周りの関数をメソッドとして持たせるのもありかなと思うんですけどどうですかね？

2018-03-11 06:07 UTC, turenar commented on src/enchant-main.ts
> +		let isRunning = false;
Coreクラス拡張でもいいけど、ドキュメントと一致してないってなって混乱しそう…… (型はドキュメントと言われればそう)

isRunningを使うのはPlayingシーンだけ？だと思うので、シーン管理の方に持たせたほうがそれっぽい気がします。もし、coreに移すなら、blocklyのコード実行中？という名前にするべきかも

2018-03-11 06:23 UTC, turenar commented on src/enchant-main.ts
> +		button.addEventListener('touchstart', function() {
全体的に、僕がJava民で、stratagyパターンに慣れてないから、他の人からするとずれてるのかもしれないのですが……

StartStopButton (現Button; 名前は適当です) としてクラスを作るならば、StartStopButtonとして明らかに実装されていなければならないもの (特にクリックハンドラのうち画像を変化させる部分) はStartStopButtonの中で登録するべきかなあと。つまり、クリックされたら (disabledになってない限り) reloadButtonは必ず呼び出されなければならないので、その処理はStartStopButtonの役割ではないかと思います。

さらに言えば、On/Offを保持して交互に画像をtoggleするボタンのクラスであれば、reloadButtonの呼び出しだけでいいと思うのですが、StartStopButtonのようにゲームのstart/stopをtoggleするようなクラスであれば、実際のstart/stop処理「呼び出し」 (あるいはcallback) までを担当するのが自然じゃないかなと思います。

resetする対象はマップやギミック等、characterだけではないと思うので、のちのち増えていくことを考えると、その管理はやっぱりシーン管理クラスとかにやらせるなりして、StartStopButtonはその管理クラスのメソッドないしcallbackを呼び出すのが自然ではないかと個人的には思います。

character.onはデバッグ用だと思って触れてませんでした。

2018-03-11 06:25 UTC, turenar commented on src/scenes.ts
> +export function initScene(character: Character, button: Button) {
Coreクラスが肥大化しそう

2018-03-12 00:45 UTC, aqla114 commented on src/scenes.ts
> +export function initScene(character: Character, button: Button) {
一理ある。

2018-03-12 00:45 UTC, aqla114 commented on src/enchant-main.ts
> +		let isRunning = false;
了解です。

2018-03-12 00:47 UTC, aqla114 commented on src/enchant-main.ts
> +		button.addEventListener('touchstart', function() {
諸々了解いたした。シーン管理クラスは必要そうなので作ります。

2018-03-12 06:51 UTC, turenar commented on src/enchant-main.ts
> +		button.addEventListener('touchstart', function() {
ゲームはオブジェクト指向と言うよりは、ゲームがオブジェクト指向言語で書かれているのが普通だったというだけで、JavaScript (/TypeScript) ならJavaScriptの主流に乗るのが良いと思います。ただ、JSは進化が激しくて昔のノウハウは今はあまり当てにならなさそう……

2018-03-12 07:47 UTC, aqla114 commented
とりあえず、こんな感じでどうでしょう。
個人的にレビュー欲しいのは、`StartStopButton`内の`listenButton`ですかね...かなり、実装が汚いので...

2018-03-12 09:52 UTC, turenar commented
![イメージしてたもの](https://user-images.githubusercontent.com/2377655/37275881-b69a3956-2623-11e8-87eb-f681d70307b1.jpg)

ぐちゃぐちゃの手書きで読みにくくてごめんなさい……頭の中にある設計を紙に起こしてみました。

つまり、スタートストップボタンってPlaying中にしか置かないからmainでインスタンスを作る理由が薄いし、
Buttonを押したときに何をresetするかはButtonが考える理由がない (Buttonはresetさえしてくれればいいが、何をresetするかはButtonが判断することではない) し、
(最初と言ってることが違うかもしれませんが) SceneManagerはSceneの入れ替えのみを担当して、Sceneが何を描画しているのかとかは知る必要がないのでは、と思います。

2018-03-12 09:56 UTC, turenar commented on src/button.ts
> +		this.addEventListener('touchstart', function() {
addEventListenerをconstructor()内に移してほしいです

2018-03-13 05:48 UTC, aqla114 commented
buttonとcharacterのコンストラクタを、PlayingSceneのコンストラクタ内で呼ぶようにしました。
sceneManagerもかなりシンプルな作りにしたのですがどうですかね。

2018-03-16 02:18 UTC, aqla114 commented
@turenar

2018-03-16 05:13 UTC, turenar commented on src/scenes.ts
> +		if (kind === 'Playing') {
何度も何度もすみません！Playing Scene固有のものは、単純に継承してPlayingSceneに移すのが良いと思います。

2018-03-16 05:13 UTC, turenar commented
これ、もしかしてFinish review押さないと見えないのか……申し訳ない…………

2018-03-16 14:11 UTC, aqla114 commented on src/scenes.ts
> +		if (kind === 'Playing') {
いえ、こちらこそ何度も何度もクソ実装をレビューしていただいて申し訳ないです。
継承しました。

2018-03-16 15:02 UTC, turenar approved these changes
ありがとうございます！

2018-03-16 15:03 UTC, merged