必要そうなブロックのコード生成を書いた
turenar/mayfes2018-pikyou pull request #71
Opened 2018-04-10 09:15 UTC by aqla114

#66 
アイテムについては未実装なので放置。他はだいたい実装した。ついでに、 #70 もやった。

2018-04-11 01:50 UTC, turenar requested changes

2018-04-11 01:50 UTC, turenar commented on src/character.ts
>  	private getFeetTile(): number {
変更箇所と関係なくて申し訳ないのですが、全体的にマップチップの種別はMapChip型で返すようにしてほしいかもです。(MapChipという名前が不適切な感じがありますが)

2018-04-11 07:34 UTC, aqla114 commented on src/character.ts
>  	private getFeetTile(): number {
ここでやらないでissue立てません？

2018-04-11 07:46 UTC, turenar commented on src/character.ts
>  	private getFeetTile(): number {
:ok_woman:

2018-04-11 08:07 UTC, aqla114 commented
他に問題なければとりあえずmergeをば。

2018-04-13 01:50 UTC, turenar approved these changes

2018-04-13 02:17 UTC, merged