Add mapchips of floor and wall
turenar/mayfes2018-pikyou pull request #85
Opened 2018-04-17 06:46 UTC by eeic19

表題通りで#56に対応です。床と壁のマップチップを変更、追加し、それに合わせて既存のものも修正しました。
壁は周囲に合わせて変えられるよう複数の画像を用意しましたが、改良案があったら教えて頂きたいです。一応stage 3に現時点での実装例が置いてあります。

2018-04-20 10:34 UTC, aqla114 requested changes
ここら辺の壁のMapChipで黒い部分が細く（小さく）なってるのって、多分立体表現なんだろうけど、ちょっと分かりにくくて違和感あるかも。太く（大きく）するか、立体感をもう少し出すかしないと、壁感が薄い？
これでもいいと思うけど、他の人の意見も聞きたさある。

![image](https://user-images.githubusercontent.com/26360576/39046563-9604187a-44d1-11e8-802c-16c2f414fcc7.png)

2018-04-20 12:56 UTC, eeic19 commented
やっぱりそうですよね(立体感のために色とかもう少し変えようとは思っていた)。実装の形に問題が無いようならそのあたりはもう一回描き直します。
ただこの実装のままだと結構stage作成とか面倒な気がするので普通に汎用チップ1枚にする案もありかと。どうしましょうかね

2018-04-21 02:51 UTC, aqla114 commented
たしかに実装めんどくさそうというのはあるなぁ。
ちなみに、汎用チップ１枚ってのはどういうのを想定している？

2018-04-21 14:32 UTC, turenar commented
すごい、めちゃくちゃそれっぽい
けど、どやくんのとおり、一ブロックの時ちょっと細すぎるかも

2018-04-23 01:36 UTC, eeic19 commented
>立体感がゴミ
改善しました(多分)
>細い
改善しました

>汎用チップ
いろいろ考えたけどやっぱり結構厳しいですね...(見た目的に)
最悪1を20-62に変換する変換プログラム作ればなんとか作業量は減らせるかな...

2018-04-23 02:01 UTC, aqla114 commented
かなり良さ。Mapchipはこれでいい気がする。
あとは、stageの記述をベタ打ちにするかどうかだけど、気持ちとしては1を20-62に変換できるシステムが欲しい気はする（62種類のMapchipを全部手打ちはかなり闇を感じるので）

2018-04-23 07:51 UTC, aqla114 approved these changes

2018-04-23 07:51 UTC, aqla114 commented
とてもいいと思います。

2018-04-23 08:12 UTC, merged