PlayingSceneを仕上げた。
turenar/mayfes2018-pikyou pull request #91
Opened 2018-04-21 13:44 UTC by aqla114

これでいいんじゃないかと思います。
![image](https://user-images.githubusercontent.com/26360576/39084812-753444b4-45b5-11e8-8f22-f717066a2201.png)

2018-04-21 14:19 UTC, turenar requested changes

2018-04-21 14:19 UTC, turenar commented on src/buttons/back-to-stageselecting-button.ts
> +export class BackToStageSelectingFromPlayingButton extends enchant.Sprite {
別ファイルに分けてください

2018-04-22 03:18 UTC, aqla114 commented on src/buttons/back-to-stageselecting-button.ts
> +export class BackToStageSelectingFromPlayingButton extends enchant.Sprite {
#76  の方で、BackToStageSelectingに好きなScene渡せるようにしたんで、BackToStageSelectingFromPlayingButtonをBackToStageSelectingにまとめてしまおうと思います。 #76 のmergeまでpendingで。

2018-04-24 14:12 UTC, aqla114 commented
ボタンのフォント変えたいのでMerge待ってください。

2018-04-30 02:12 UTC, aqla114 commented
@turenar 
PlayingSceneのUI完成させてhoverも実装したのでreviewお願いします。

2018-04-30 10:07 UTC, turenar commented on src/buttons/back-to-stageselecting-button.ts
> +				this.image = core.assets['img/back_to_stage_selecting_from_playing_button_hover.png'];
constructorのimagePath/imageHoverPathをつかってないのと、ホバー処理あたりをButtonクラスとかに共通化してほしさあります

2018-04-30 11:01 UTC, aqla114 commented on src/buttons/back-to-stageselecting-button.ts
> +				this.image = core.assets['img/back_to_stage_selecting_from_playing_button_hover.png'];
＋蟹。

2018-04-30 12:52 UTC, aqla114 commented
Buttonのベースのクラス作りました。

2018-04-30 14:18 UTC, turenar commented on src/buttons/button.ts
> +		if (!(this instanceof StartStopButton)) {
外から (あるいはimageHoverPath == null) で区別するほうがいいと思う

imagePathをButton#constructorでthis.imageに設定してあげてもいいと思うけどどっちでもいいや

2018-05-01 02:40 UTC, aqla114 commented
StartStopButtonだけ処理が特殊すぎるんで、そもそもButtonを継承しないようにしました。
あとは、imageHoverPath==nullで区別してます。

2018-05-01 13:39 UTC, turenar commented
## 案1

enterframeイベントリスナーの中で、this.onMouseEnter / this.onMouseLeave (/Exit) (あるいはonHover /onUnhover) を呼び出すようにして、継承先で２つの関数をoverrideしimageを適切に設定する

touchendもonTouchEndとかで用意するときれいかも

## 案2

imagePath/hoverImagePathをインスタンス変数として持つようにして、StartStopButton#reloadButton内で(hover)imagePathを設定する

2018-05-02 02:08 UTC, aqla114 commented
えっと、この案というのはStartStopButtonもButtonを継承するようにするための実装案、という解釈でいいですか？

2018-05-02 04:39 UTC, turenar commented
そうっす、すみません、いつも言葉が足りなくて

2018-05-02 06:59 UTC, aqla114 commented
案１を採用しました（が、結果として案２も採用することになってしまった）

2018-05-02 08:07 UTC, turenar approved these changes

2018-05-02 08:07 UTC, merged