Share clear situation in all stages
turenar/mayfes2018-pikyou pull request #95
Opened 2018-04-22 15:33 UTC by tkygtr6

#92 #93 の実装を済ませました

補足ですが、scenes/scenes.tsのSceneオブジェクトのインスタンス変数のSceneManagerをprivateからprotectedにしたのは、継承先のStageSelectingSceneからアクセスできるようにするためです。

2018-04-24 13:55 UTC, aqla114 requested changes
見るのが遅くなって申し訳ないです。
気になった箇所コメントしておいたので、修正してくれると嬉しいです。

2018-04-24 13:55 UTC, aqla114 commented on src/enchant/stage-labels.ts
> +		this.scoreLabel.text = 'score: ' + clearSituation.score.toString();
ここ、template literal使った方がきれいだと思う（他の文字列を結合する場所も同様）。

2018-04-24 13:55 UTC, aqla114 commented on src/score-manager.ts
> +}
これ、classで定義しなくても、

```
type clearSituation = { isCleard: boolean; score: number }; 
```

で十分な気がします（どこかでクラスにする必要があったならごめんなさい）。

2018-04-24 13:55 UTC, aqla114 commented on src/scene-manager.ts
> +	public getMaxCanSelectStageNum() {
これはかなり英語のお話なんですけど、getMaxOfSelectableStageNumberとかにしませんか？

2018-04-25 04:08 UTC, turenar requested changes

2018-04-25 04:08 UTC, turenar commented on src/score-manager.ts
> +}
ついでに、型名はCamelCaseにしてほしさある

クラス名とファイル名も揃えてほしいな

2018-04-25 04:08 UTC, turenar commented on src/scenes/stage-selecting-scene.ts
> +		console.log(this.manager.getMaxCanSelectStageNum());
console.logは残すなら説明的にしてください

```console.log({ maxSelectableStage: this.manager.getMaxCanSelectStageNum() });```

削除でも大丈夫です

2018-04-25 04:08 UTC, turenar commented on src/scene-manager.ts
> +	public updateScore(stageNum: number, score: number) {
この先、Cookieかどこかに保存・読み込みする処理が入ってくるから、このあたりはメインの処理はScoreManagerとかにやらせてほしいかも。

2018-04-26 08:52 UTC, tkygtr6 commented
@turenar @aqla114 レビューありがとうございます、修正しました。

2018-04-27 11:10 UTC, aqla114 commented on src/enchant/stage-labels.ts
> +		this.stageNumLabel.text = `ステージ ${(stageNum + 1).toString()}`;
template literalは勝手に式展開してstring化してくれるので、toString()無しで良いです。

2018-04-27 12:08 UTC, aqla114 approved these changes
いいと思います。

2018-04-28 04:35 UTC, turenar approved these changes

2018-04-28 04:37 UTC, merged